### ISSUE TITLE
cannot download for timeout

### ISSUE THREAD

**Issue by scottyan19** [AdoptOpenJDK/openjdk-jdk11u#12]
Hi all, I'm from China, and as you know, my internet connection(bandwidth) is not so good,  download speed is a little slow , but "should" work.   

however!! I found adoptOpenJdk download has a timeout limitation!!  I've tried for several times, every time, when the download percentage reach 80%,  the download stopped, because link is timeout, I must restart from the beginning,  which means, I can never complete my download. 

well, I understand you don't want to provide a permanent link , but could you please make the timeout limit a little bit longer?  at least for some hours?  not everyone has a very fast internet connection......  

Thanks~

**Comment by johnoliver** [comment]
We simply link to the github release download link. If there is a timeout it would be github or possibly amazon (I believe github backs on to S3) that control this, we cannot.

**Comment by scottyan19** [comment]
> We simply link to the github release download link. If there is a timeout it would be github or possibly amazon (I believe github backs on to S3) that control this, we cannot.

OK, roger that,  thanks for your reply~
