### ISSUE TITLE
WM_CLASS property

### ISSUE THREAD

**Issue by admincheg** [AdoptOpenJDK/openjdk-jdk11u#13]
Hello.

We're found interesting behavior at this line:

https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/770ef496e67e318ea5418609b83cf0304761e210/src/java.desktop/unix/classes/sun/awt/X11/XRootWindow.java#L66

I think it will be better if you can give abilities to programmer for two statements:

1. Set two different strings for WM_CLASS (for example - first is application name, second is a window type - panel, main window, menu, etc)
2. Interfaces for setting this properties instead of reflection using

**Comment by admincheg** [comment]
At this time for changing WM_CLASS we should make reflection, make property accessible and set to our value. It's not clean, I think.

https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/770ef496e67e318ea5418609b83cf0304761e210/src/java.desktop/unix/classes/sun/awt/X11/XToolkit.java#L170

**Comment by admincheg** [comment]
Additional interesting thing - using WM_CLASS for setting window title.

https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/770ef496e67e318ea5418609b83cf0304761e210/src/java.desktop/unix/classes/sun/awt/X11/XRootWindow.java#L63

As I know this is a two different kinds of information. WM_CLASS is a technical information for window managers, but window name is an information for end users.

I think window name should by an additional separated field with getters/setter.

**Comment by karianna** [comment]
@admincheg - This suggestion should be reported at the OpenJDK upstream project.

https://mail.openjdk.java.net/mailman/listinfo/awt-dev
