### ISSUE TITLE
Hardened runtime issue in macOS, missing audio-input entitlement

### ISSUE THREAD

**Issue by adruiza** [AdoptOpenJDK/openjdk-jdk11u#16]
As explained in https://github.com/AdoptOpenJDK/openjdk-build/issues/1720, the JDK is missing some entitlements in macOS and this causes TCC to block microphone access automatically because of the hardened runtime access restrictions.

No dialog appears to confirm microphone access and there is no way to manually add Java to the list of applications allowed to access the microphone, so virtually, there is no way to use the microphone when running .jar files through the command line.

I haven't tested all other protected resources (camera, etc), I guess they will fail too, but I can confirm that accessing "Downloads", "Documents" and "Desktop", which are protected directories, triggers the authorization dialog, so directory access seems fine.

**Comment by karianna** [comment]
We'll resolve this in the build scripts
